import { useTranslation } from "react-i18next";

export const useProjectsDetail = () => {
  const { t } = useTranslation();

  return [
    {
      id: 1,
      title: t("projects.icontrol.title"),
      shortDescription: t("projects.icontrol.shortDescription"),
      fullDescription: t("projects.icontrol.fullDescription"),
      images: [
        "/projects/icontrol1.png",
        "/projects/icontrol2.png",
        "/projects/icontrol3.png",
        "/projects/icontrol4.png",
        "/projects/icontrol5.png",
        "/projects/icontrol6.png",
        "/projects/icontrol7.png",
      ],
      technologies: [
        "React",
        "TypeScript",
        "Node.js",
        "PostgreSQL",
        "Docker",
        t("projects.technologies.microservices"),
        "Leaflet",
        "Cloudinary",
        "JWT",
        "BullMQ",
        "Redis",
        "Tailwind CSS",
      ],
      problem: t("projects.icontrol.problem"),
      solution: t("projects.icontrol.solution"),
      features: [
        t("projects.icontrol.features.1"),
        t("projects.icontrol.features.2"),
        t("projects.icontrol.features.3"),
        t("projects.icontrol.features.4"),
        t("projects.icontrol.features.5"),
        t("projects.icontrol.features.6"),
        t("projects.icontrol.features.7"),
        t("projects.icontrol.features.8"),
      ],
      challenges: [
        t("projects.icontrol.challenges.1"),
        t("projects.icontrol.challenges.2"),
        t("projects.icontrol.challenges.3"),
        t("projects.icontrol.challenges.4"),
        t("projects.icontrol.challenges.5"),
      ],
      achievements: [
        t("projects.icontrol.achievements.1"),
        t("projects.icontrol.achievements.2"),
        t("projects.icontrol.achievements.3"),
        t("projects.icontrol.achievements.4"),
        t("projects.icontrol.achievements.5"),
      ],
      demoUrl: "https://icontrol-app-isp-lilac.vercel.app",
      codeUrl: "https://github.com/tu-usuario/icontrol-system",
      type: "fullstack",
    },

    {
      id: 2,
      title: t("projects.vetclinic.title"),
      shortDescription: t("projects.vetclinic.shortDescription"),
      fullDescription: t("projects.vetclinic.fullDescription"),
      images: [
        "/projects/vet1.png",
        "/projects/vet2.png",
        "/projects/vet3.png",
        "/projects/vet4.png",
        "/projects/vet5.png",
        "/projects/vet6.png",
        "/projects/vet7.png",
        "/projects/vet8.png",
      ],
      technologies: [
        "C#",
        ".NET Framework",
        "WinForms",
        "SQL Server",
        t("projects.technologies.tsql"),
        "LINQ",
        t("projects.technologies.adonet"),
        t("projects.technologies.oop"),
      ],
      problem: t("projects.vetclinic.problem"),
      solution: t("projects.vetclinic.solution"),
      features: [
        t("projects.vetclinic.features.1"),
        t("projects.vetclinic.features.2"),
        t("projects.vetclinic.features.3"),
        t("projects.vetclinic.features.4"),
        t("projects.vetclinic.features.5"),
        t("projects.vetclinic.features.6"),
        t("projects.vetclinic.features.7"),
      ],
      challenges: [
        t("projects.vetclinic.challenges.1"),
        t("projects.vetclinic.challenges.2"),
        t("projects.vetclinic.challenges.3"),
        t("projects.vetclinic.challenges.4"),
        t("projects.vetclinic.challenges.5"),
      ],
      achievements: [
        t("projects.vetclinic.achievements.1"),
        t("projects.vetclinic.achievements.2"),
        t("projects.vetclinic.achievements.3"),
        t("projects.vetclinic.achievements.4"),
        t("projects.vetclinic.achievements.5"),
      ],
      demoUrl: "",
      codeUrl: "https://github.com/Dantell12/Veterinary-Clinic-Sys.git",
      type: "desktop",
    },
    {
      id: 3,
      title: t("projects.biblio.title"),
      shortDescription: t("projects.biblio.shortDescription"),
      fullDescription: t("projects.biblio.fullDescription"),
      images: [
        "/projects/biblio1.png",
        "/projects/biblio2.png",
        "/projects/biblio3.png",
        "/projects/biblio4.png",
        "/projects/biblio5.png",
        "/projects/biblio6.png",
      ],
      technologies: [
        "C#",
        "Visual Studio",
        "SQL Server",
        t("projects.technologies.storedProcedures"),
        t("projects.technologies.erModeling"),
      ],
      problem: t("projects.biblio.problem"),
      solution: t("projects.biblio.solution"),
      features: [
        t("projects.biblio.features.1"),
        t("projects.biblio.features.2"),
        t("projects.biblio.features.3"),
        t("projects.biblio.features.4"),
      ],
      challenges: [
        t("projects.biblio.challenges.1"),
        t("projects.biblio.challenges.2"),
        t("projects.biblio.challenges.3"),
      ],
      achievements: [
        t("projects.biblio.achievements.1"),
        t("projects.biblio.achievements.2"),
        t("projects.biblio.achievements.3"),
      ],
      codeUrl: "https://github.com/Dantell12/System-Bibliografy-Utmach.git",
      demo: null,
    },

    {
      id: 4,
      title: t("projects.email.title"),
      shortDescription: t("projects.email.shortDescription"),
      fullDescription: t("projects.email.fullDescription"),
      images: [
        "/projects/email1.png",
        "/projects/email2.png",
        "/projects/email3.png",
        "/projects/email4.png",
        "/projects/email5.png",
      ],
      technologies: [
        "Python",
        "Scikit-learn",
        "XGBoost",
        "Random Forest",
        "Logistic Regression",
        "Naive Bayes",
        "KNN",
        "SVC",
        "MLP",
        "Pandas",
        "Matplotlib",
      ],
      problem: t("projects.email.problem"),
      solution: t("projects.email.solution"),
      features: [
        t("projects.emailo.features.1"),
        t("projects.emailo.features.2"),
        t("projects.emailo.features.3"),
        t("projects.emailo.features.4"),
      ],
      challenges: [
        t("projects.email.challenges.1"),
        t("projects.email.challenges.2"),
        t("projects.email.challenges.3"),
      ],
      achievements: [
        t("projects.email.achievements.1"),
        t("projects.email.achievements.2"),
        t("projects.email.achievements.3"),
      ],
      codeUrl: "https://github.com/Dantell12/Email-Classifier.git",
      demo: null,
      document:
        "https://drive.google.com/file/d/1CVo8hzMosBMQeSn3fMZL6yDPH6o2b0bL/view?usp=sharing",
    },
    {
      id: 5,
      title: t("projects.shoemarket.title"),
      shortDescription: t("projects.shoemarket.shortDescription"),
      fullDescription: t("projects.shoemarket.fullDescription"),
      images: [
        "/projects/market1.png",
        "/projects/market2.png",
        "/projects/market3.png",
        "/projects/market4.png",
        "/projects/market5.png",
      ],
      technologies: [
        "React",
        "Vite",
        "TypeScript",
        "Tailwind CSS",
        "Node.js",
        "TypeScript (Node)",
        "Sequelize",
        "PostgreSQL",
        "JWT",
        "Stripe (simulado)",
        "Chart.js",
      ],
      problem: t("projects.shoemarket.problem"),
      solution: t("projects.shoemarket.solution"),
      features: [
        t("projects.shoemarket.features.1"),
        t("projects.shoemarket.features.2"),
        t("projects.shoemarket.features.3"),
        t("projects.shoemarket.features.4"),
        t("projects.shoemarket.features.5"),
        t("projects.shoemarket.features.6"),
        t("projects.shoemarket.features.7"),
        t("projects.shoemarket.features.8"),
      ],

      challenges: [
        t("projects.shoemarket.challenges.1"),
        t("projects.shoemarket.challenges.2"),
        t("projects.shoemarket.challenges.3"),
        t("projects.shoemarket.challenges.4"),
        t("projects.shoemarket.challenges.5"),
      ],
      achievements: [
        t("projects.shoemarket.achievements.1"),
        t("projects.shoemarket.achievements.2"),
        t("projects.shoemarket.achievements.3"),
        t("projects.shoemarket.achievements.4"),
        t("projects.shoemarket.achievements.5"),
      ],
      codeUrl: "https://github.com/Dantell12/website-market/",
      demo: null,
      document: null,
      type: "fullstack",
    },
  ];
};
