import { useMemo } from "react";
import { useTranslation } from "react-i18next";

// Datos estáticos movidos fuera del componente para evitar recreación
const STATIC_PROJECTS_DATA = [
  {
    id: 1,
    titleKey: "projects.icontrol.title",
    shortDescriptionKey: "projects.icontrol.shortDescription",
    fullDescriptionKey: "projects.icontrol.fullDescription",
    images: [
      "/projects/icontrol1.png",
      "/projects/icontrol2.png",
      "/projects/icontrol3.png",
      "/projects/icontrol4.png",
      "/projects/icontrol5.png",
      "/projects/icontrol6.png",
      "/projects/icontrol7.png",
    ],
    staticTechnologies: [
      "React",
      "TypeScript",
      "Node.js",
      "PostgreSQL",
      "Docker",
      "Leaflet",
      "Cloudinary",
      "JWT",
      "BullMQ",
      "Redis",
      "Tailwind CSS",
    ],
    dynamicTechnologies: ["projects.technologies.microservices"],
    problemKey: "projects.icontrol.problem",
    solutionKey: "projects.icontrol.solution",
    featuresKeys: [
      "projects.icontrol.features.1",
      "projects.icontrol.features.2",
      "projects.icontrol.features.3",
      "projects.icontrol.features.4",
      "projects.icontrol.features.5",
      "projects.icontrol.features.6",
      "projects.icontrol.features.7",
      "projects.icontrol.features.8",
    ],
    challengesKeys: [
      "projects.icontrol.challenges.1",
      "projects.icontrol.challenges.2",
      "projects.icontrol.challenges.3",
      "projects.icontrol.challenges.4",
      "projects.icontrol.challenges.5",
    ],
    achievementsKeys: [
      "projects.icontrol.achievements.1",
      "projects.icontrol.achievements.2",
      "projects.icontrol.achievements.3",
      "projects.icontrol.achievements.4",
      "projects.icontrol.achievements.5",
    ],
    demoUrl: "https://icontrol-app-isp-lilac.vercel.app",
    codeUrl: "https://github.com/tu-usuario/icontrol-system",
    type: "fullstack",
  },
  {
    id: 2,
    titleKey: "projects.vetclinic.title",
    shortDescriptionKey: "projects.vetclinic.shortDescription",
    fullDescriptionKey: "projects.vetclinic.fullDescription",
    images: [
      "/projects/vet1.png",
      "/projects/vet2.png",
      "/projects/vet3.png",
      "/projects/vet4.png",
      "/projects/vet5.png",
      "/projects/vet6.png",
      "/projects/vet7.png",
      "/projects/vet8.png",
    ],
    staticTechnologies: [
      "C#",
      ".NET Framework",
      "WinForms",
      "SQL Server",
      "LINQ",
    ],
    dynamicTechnologies: [
      "projects.technologies.tsql",
      "projects.technologies.adonet",
      "projects.technologies.oop",
    ],
    problemKey: "projects.vetclinic.problem",
    solutionKey: "projects.vetclinic.solution",
    featuresKeys: [
      "projects.vetclinic.features.1",
      "projects.vetclinic.features.2",
      "projects.vetclinic.features.3",
      "projects.vetclinic.features.4",
      "projects.vetclinic.features.5",
      "projects.vetclinic.features.6",
      "projects.vetclinic.features.7",
    ],
    challengesKeys: [
      "projects.vetclinic.challenges.1",
      "projects.vetclinic.challenges.2",
      "projects.vetclinic.challenges.3",
      "projects.vetclinic.challenges.4",
      "projects.vetclinic.challenges.5",
    ],
    achievementsKeys: [
      "projects.vetclinic.achievements.1",
      "projects.vetclinic.achievements.2",
      "projects.vetclinic.achievements.3",
      "projects.vetclinic.achievements.4",
      "projects.vetclinic.achievements.5",
    ],
    demoUrl: "",
    codeUrl: "https://github.com/Dantell12/Veterinary-Clinic-Sys.git",
    type: "desktop",
  },
  {
    id: 3,
    titleKey: "projects.biblio.title",
    shortDescriptionKey: "projects.biblio.shortDescription",
    fullDescriptionKey: "projects.biblio.fullDescription",
    images: [
      "/projects/biblio1.png",
      "/projects/biblio2.png",
      "/projects/biblio3.png",
      "/projects/biblio4.png",
      "/projects/biblio5.png",
      "/projects/biblio6.png",
    ],
    staticTechnologies: ["C#", "Visual Studio", "SQL Server"],
    dynamicTechnologies: [
      "projects.technologies.storedProcedures",
      "projects.technologies.erModeling",
    ],
    problemKey: "projects.biblio.problem",
    solutionKey: "projects.biblio.solution",
    featuresKeys: [
      "projects.biblio.features.1",
      "projects.biblio.features.2",
      "projects.biblio.features.3",
      "projects.biblio.features.4",
    ],
    challengesKeys: [
      "projects.biblio.challenges.1",
      "projects.biblio.challenges.2",
      "projects.biblio.challenges.3",
    ],
    achievementsKeys: [
      "projects.biblio.achievements.1",
      "projects.biblio.achievements.2",
      "projects.biblio.achievements.3",
    ],
    codeUrl: "https://github.com/Dantell12/System-Bibliografy-Utmach.git",
    demo: null,
  },
  {
    id: 4,
    titleKey: "projects.email.title",
    shortDescriptionKey: "projects.email.shortDescription",
    fullDescriptionKey: "projects.email.fullDescription",
    images: [
      "/projects/email1.png",
      "/projects/email2.png",
      "/projects/email3.png",
      "/projects/email4.png",
      "/projects/email5.png",
    ],
    staticTechnologies: [
      "Python",
      "Scikit-learn",
      "XGBoost",
      "Random Forest",
      "Logistic Regression",
      "Naive Bayes",
      "KNN",
      "SVC",
      "MLP",
      "Pandas",
      "Matplotlib",
    ],
    dynamicTechnologies: [],
    problemKey: "projects.email.problem",
    solutionKey: "projects.email.solution",
    featuresKeys: [
      "projects.emailo.features.1",
      "projects.emailo.features.2",
      "projects.emailo.features.3",
      "projects.emailo.features.4",
    ],
    challengesKeys: [
      "projects.email.challenges.1",
      "projects.email.challenges.2",
      "projects.email.challenges.3",
    ],
    achievementsKeys: [
      "projects.email.achievements.1",
      "projects.email.achievements.2",
      "projects.email.achievements.3",
    ],
    codeUrl: "https://github.com/Dantell12/Email-Classifier.git",
    demo: null,
    document:
      "https://drive.google.com/file/d/1CVo8hzMosBMQeSn3fMZL6yDPH6o2b0bL/view?usp=sharing",
  },
  {
    id: 5,
    titleKey: "projects.shoemarket.title",
    shortDescriptionKey: "projects.shoemarket.shortDescription",
    fullDescriptionKey: "projects.shoemarket.fullDescription",
    images: [
      "/projects/market1.png",
      "/projects/market2.png",
      "/projects/market3.png",
      "/projects/market4.png",
      "/projects/market5.png",
    ],
    staticTechnologies: [
      "React",
      "Vite",
      "TypeScript",
      "Tailwind CSS",
      "Node.js",
      "TypeScript (Node)",
      "Sequelize",
      "PostgreSQL",
      "JWT",
      "Stripe (simulado)",
      "Chart.js",
    ],
    dynamicTechnologies: [],
    problemKey: "projects.shoemarket.problem",
    solutionKey: "projects.shoemarket.solution",
    featuresKeys: [
      "projects.shoemarket.features.1",
      "projects.shoemarket.features.2",
      "projects.shoemarket.features.3",
      "projects.shoemarket.features.4",
      "projects.shoemarket.features.5",
      "projects.shoemarket.features.6",
      "projects.shoemarket.features.7",
      "projects.shoemarket.features.8",
    ],
    challengesKeys: [
      "projects.shoemarket.challenges.1",
      "projects.shoemarket.challenges.2",
      "projects.shoemarket.challenges.3",
      "projects.shoemarket.challenges.4",
      "projects.shoemarket.challenges.5",
    ],
    achievementsKeys: [
      "projects.shoemarket.achievements.1",
      "projects.shoemarket.achievements.2",
      "projects.shoemarket.achievements.3",
      "projects.shoemarket.achievements.4",
      "projects.shoemarket.achievements.5",
    ],
    codeUrl: "https://github.com/Dantell12/website-market/",
    demo: null,
    document: null,
    type: "fullstack",
  },
];

export const useProjectsDetail = () => {
  const { t } = useTranslation();

  return useMemo(
    () =>
      STATIC_PROJECTS_DATA.map((project) => ({
        id: project.id,
        title: t(project.titleKey),
        shortDescription: t(project.shortDescriptionKey),
        fullDescription: t(project.fullDescriptionKey),
        images: project.images,
        technologies: [
          ...project.staticTechnologies,
          ...project.dynamicTechnologies.map((key) => t(key)),
        ],
        problem: t(project.problemKey),
        solution: t(project.solutionKey),
        features: project.featuresKeys.map((key) => t(key)),
        challenges: project.challengesKeys.map((key) => t(key)),
        achievements: project.achievementsKeys.map((key) => t(key)),
        demoUrl: project.demoUrl,
        codeUrl: project.codeUrl,
        demo: project.demo || null,
        document: project.document || null,
        type: project.type || null,
      })),
    [t]
  );
};